
############################################
#  Date:2021.1.4 
#                                       
#   SERVICES:                              
#   1. Elasticsearch 7.10.1                 
#   2. Kibana 7.10.1                        
#                        
#   RUN:
#     docker-compose up
#     访问：localhost:5601                  
############################################

version: "3.0"

services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: kibana:7.10.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - I18N_LOCALE="zh-CN"
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - esnet
volumes:
  esdata:
    driver: local
    driver_opts: 
      device: /tmp/esdata
networks:
  esnet: